# Generated by Django 2.2.3 on 2019-07-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyrecord',
            name='all_time',
            field=models.FloatField(default=0.0, verbose_name='学习总时间'),
        ),
    ]
