# Generated by Django 2.2.3 on 2019-08-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_studyrecord_all_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='', verbose_name='头像'),
        ),
    ]
