# Generated by Django 2.2.3 on 2019-08-04 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_auto_20190803_2243'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='studyrecord',
            table='ss_study_record',
        ),
    ]
